/*
 * generated by Xtext
 */
package de.abg.jreichert.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TargetDefinitionUiModule extends de.abg.jreichert.ui.AbstractTargetDefinitionUiModule {
	public TargetDefinitionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
