/*
* generated by Xtext
*/
package de.abg.jreichert.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class TargetDefinitionOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
