/*
 * generated by Xtext
 */
package de.abg.jreichert.repositorytarget.dsl;

/**
 * Initialization support for running Xtext languages without equinox extension registry
 */
public class TargetDefinitionStandaloneSetup extends TargetDefinitionStandaloneSetupGenerated {

	@SuppressWarnings("javadoc")
	public static void doSetup() {
		new TargetDefinitionStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
