/*
 * generated by Xtext
 */
package de.abg.jreichert.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.abg.jreichert.ui.internal.TargetDefinitionActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TargetDefinitionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TargetDefinitionActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TargetDefinitionActivator.getInstance().getInjector(TargetDefinitionActivator.DE_ABG_JREICHERT_TARGETDEFINITION);
	}
	
}
