/*
 * generated by Xtext
 */
package de.abg.jreichert;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TargetDefinitionRuntimeModule extends de.abg.jreichert.AbstractTargetDefinitionRuntimeModule {

}
