/*
* generated by Xtext
*/
package de.abg.jreichert.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TargetDefinitionAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/abg/jreichert/parser/antlr/internal/InternalTargetDefinition.tokens");
	}
}
