/*
* generated by Xtext
*/
package de.abg.jreichert.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.abg.jreichert.services.TargetDefinitionGrammarAccess;

public class TargetDefinitionParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TargetDefinitionGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.abg.jreichert.parser.antlr.internal.InternalTargetDefinitionParser createParser(XtextTokenStream stream) {
		return new de.abg.jreichert.parser.antlr.internal.InternalTargetDefinitionParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Target";
	}
	
	public TargetDefinitionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TargetDefinitionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
